### ISSUE TITLE
Writing log files?

### ISSUE THREAD

**Issue by ellisthedev** [shpasser/GaeSupportL5#1]
First off, awesome package. Installing this, changing a couple settings, and seeing Laravel running on GAE is amazing.

However, by default the Logger is trying to write to our bucket and we are seeing the following error in the GAE logs:

```
PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "gs://cl-members/storage/logs/laravel-2015-02-20.log" could not be opened: failed to open stream: "\google\appengine\ext\cloud_storage_streams\CloudStorageStreamWrapper::stream_open" call failed' in /base/data/home/apps/s~cl-members/1.382361638587654395/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:84
Stack trace:
#0 /base/data/home/apps/s~cl-members/1.382361638587654395/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(88): Monolog\Handler\StreamHandler->write(Array)
#1 /base/data/home/apps/s~cl-members/1.382361638587654395/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#2 /base/data/home/apps/s~cl-members/1.382361638587654395/vendor/monolog/monolog/src/Monolog/Logger.php(265): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#3 /base/data/home/apps/s~cl-members/1.382361638587654395/vendor/monolog/monolog/src/Mo in /base/data/home/apps/s~cl-members/1.382361638587654395/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 84
```

What is odd is Laravel is successfully creating the `gs://cl-members/storage/framework` stuff... Any ideas on how to proceed? I tried manually creating the `gs://cl-members/storage/logs` directory, but the same error persists.

**Comment by shpasser** [comment]
The only supported log handler for GAE is 'syslog' (I will to mention it in the readme file).
By default your '.env.production' file 
should contain the line:
```php
LOG_HANDLER = syslog
```
and your `config/app.php` file should contain the line:
```php
'log' => env('LOG_HANDLER', 'daily'),
```

These lines are generated by the `php artisan gae:setup` command.

As for the reason causing the issue, GAE support for `fopen()` is:

`fopen — Opens file or URL.	Supported.	Only supports these modes: r, rb, rt, w, wb, wt.`

Take a look at GAE file management support table:
https://cloud.google.com/appengine/docs/php/googlestorage/advanced#php_filesystem_functions_support_on_google_cloud_storage

The monolog `StreamHandler` uses `fopen()` with 'a' mode which is not supported for GAE buckets.

It is possible to alter the monolog code, which I don't like, or write a new handler supporting the 
GAE buckets. Anyway we would end up with something like:
```php

$tempDir = sys_get_temp_dir();
$tempLogFile = tempnam($tempDir, basename($this->url));
$logContents = file_get_contents($this->url);
file_put_contents($tempLogFile, $logContents);
...
$tempLog = fopen($tempLogFile, “a”);
...
fwrite($tempLog, (string) $record['formatted']);
fclose($tempLog);

$updatedLogContents = file_get_contents($tempLogFile);
file_put_contents($this->url, $updatedLogContents );
...
```
Let me know if this helps.

Best,

Ron.

**Comment by ellisthedev** [comment]
Hey Ron,

Thank you so much for the detailed response. It appears I missed the very last bit in your README about setting `.env.production` to `.env` before deploying. This falls under the RTFM category.

Now if I could just get `appcfg.py` to deploy my app I could test this is actually working. Stupid thing is stuck in the `Checking if deployment succeeded.` loop :(

Cheers,
-Andrew
