### ISSUE TITLE
GaeSupportL5 blocks Laravel 5.1 update because of illuminate/support 5.0.* dependency.

### ISSUE THREAD

**Issue by mmikulski** [shpasser/GaeSupportL5#14]
I was trying to update my Laravel app to recently released 5.1 version but GaeSupportL5 dependency on illuminate/support 5.0.* blocked the update.
Composer response:
<pre>
$>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel/framework v5.1.1
    - shpasser/gae-support-l5 1.2.1 requires illuminate/support 5.0.* -> satisfiable by laravel/framework[v5.0.32], illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.
0.33, v5.0.4].
    - shpasser/gae-support-l5 1.0 requires illuminate/support 5.0.* -> satisfiable by laravel/framework[v5.0.32], illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.
33, v5.0.4].
    - shpasser/gae-support-l5 1.1 requires illuminate/support 5.0.* -> satisfiable by laravel/framework[v5.0.32], illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.
33, v5.0.4].
    - shpasser/gae-support-l5 1.1.1 requires illuminate/support 5.0.* -> satisfiable by laravel/framework[v5.0.32], illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.
0.33, v5.0.4].
    - shpasser/gae-support-l5 1.1.2 requires illuminate/support 5.0.* -> satisfiable by laravel/framework[v5.0.32], illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.
0.33, v5.0.4].
    - shpasser/gae-support-l5 1.2 requires illuminate/support 5.0.* -> satisfiable by laravel/framework[v5.0.32], illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.
33, v5.0.4].
    - shpasser/gae-support-l5 1.2.1 requires illuminate/support 5.0.* -> satisfiable by laravel/framework[v5.0.32], illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.
0.33, v5.0.4].
    - Can only install one of: laravel/framework[v5.1.0, v5.0.32].
    - don't install illuminate/support v5.0.0|don't install laravel/framework v5.1.0
    - don't install illuminate/support v5.0.22|don't install laravel/framework v5.1.0
    - don't install illuminate/support v5.0.25|don't install laravel/framework v5.1.0
    - don't install illuminate/support v5.0.26|don't install laravel/framework v5.1.0
    - don't install illuminate/support v5.0.28|don't install laravel/framework v5.1.0
    - don't install illuminate/support v5.0.33|don't install laravel/framework v5.1.0
    - don't install illuminate/support v5.0.4|don't install laravel/framework v5.1.0
    - Installation request for laravel/framework 5.1.* -> satisfiable by laravel/framework[v5.1.0, v5.1.1].
    - Installation request for shpasser/gae-support-l5 1.* -> satisfiable by shpasser/gae-support-l5[1.0, 1.1, 1.1.1, 1.1.2, 1.2, 1.2.1].
</pre>

**Comment by shpasser** [comment]
I would try changing "5.0.*" to "~5.0" in `composer.json` (`gae-support` package). I'm going to take a look at it later today.

**Comment by mmikulski** [comment]
Thanks for the suggestion.
I've created local version of the package with 
<pre>"illuminate/support": "5.1.*",</pre>

Composer update went well until getting to generation of autoload files.

The problem was with missing "useStoragePathForOptimizations()" called  in Application class constructor.
Mwthod was removed from 5.1 version of "Illuminate\Foundation\Application.php".
I have replaced
<pre>$this->useStoragePathForOptimizations();</pre>
with 
<pre>
if ($basePath) {
            $this->setBasePath($basePath);
        }
</pre>
in class constructor.
Everything seems to be working fine, but it may be only first impression ;)

**Comment by shpasser** [comment]
The optimizations won't work. I'll have to rewrite some code (change some paths) to make the package compatible. The upcoming stable release is going to be compatible with Laravel 5.1.

**Comment by shpasser** [comment]
Updated for Laravel 5.1, the new stable version is 1.3.

**Comment by mmikulski** [comment]
@shpasser Many thanks for quick update.
It works like a charm.

**Comment by shpasser** [comment]
Cool, thanks.
