### ISSUE TITLE
Class cache does not exist

### ISSUE THREAD

**Issue by tusharvikky** [shpasser/GaeSupportL5#17]
Hello,

If I enable memcached in localhost it throws ReflectionException "Class cache does not exist", This same happens while deploying.

**Comment by shpasser** [comment]
In order to use "memcached" you would need to have a "memcahched" server and "php5-memcached" installed on your machine (for Ubuntu).
The local configuration generated by "php artisan gae:setup" does not contain "memcached". You should use the ".env.production" for generating the optimized files and for the deployment on GAE. If you wish to work locally, remove the generated optimized files and switch to ".env.local".
Let me know if this helps.

**Comment by shpasser** [comment]
Sometimes problems can be caused by an outdated `compiled.php` file. Try removing `your-app/vendor/compiled.php`, it might help.

**Comment by shpasser** [comment]
If I see no progress on this issue in 3 day I will have to close it. Please respond.

**Comment by tusharvikky** [comment]
I did try this. I even had memcache installed. But it didn't work. Might have to move to Google Compute Engine.

**Comment by shpasser** [comment]
If you still want help on this one please describe your development environment including the Operation System, PHP version `.env` files you use for local and production. I would need also the description of your workflow i.e. commands you execute including parameters.

**Comment by shpasser** [comment]
I've updated some code. Not something critical, but you might want to update the package.

**Comment by tusharvikky** [comment]
Updated the repo. 

Dev env details: 
OS: Linux Ubuntu 14.04
php -v: 5.5.9

Local:
```
APP_ENV=local
APP_DEBUG=true
APP_KEY=a5uFutg9ScVhqVmiIMg6JWksuWK4rBtM
DB_HOST=localhost
DB_DATABASE=db1
DB_USERNAME=root
DB_PASSWORD=root
CACHE_DRIVER=memcached
SESSION_DRIVER=memcached
QUEUE_DRIVER=sync
MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=
DB_CONNECTION=sql
CLOUD_SQL_SOCKET=
CLOUD_SQL_HOST=cloud-sql-instance-ipv4-address
CLOUD_SQL_DATABASE=cloud-sql-database-name
CLOUD_SQL_USERNAME=root
CLOUD_SQL_PASSWORD=password
```
Prod:
```
APP_ENV=production
APP_DEBUG=false
APP_KEY=a5uFutg9ScVhqVmiIMg6JWksuWK4rBtM
DB_HOST=localhost
DB_DATABASE=db1
DB_USERNAME=root
DB_PASSWORD=root
CACHE_DRIVER=memcached
SESSION_DRIVER=memcached
QUEUE_DRIVER=gae
MAIL_DRIVER=gae
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=
LOG_HANDLER=syslog
FILESYSTEM=gae
DB_CONNECTION=cloudsql
CLOUD_SQL_SOCKET=string
CLOUD_SQL_HOST=
CLOUD_SQL_DATABASE=db1
CLOUD_SQL_USERNAME=root
CLOUD_SQL_PASSWORD=pass
COMPILED_PATH = cachefs://framework/views
```
php -m:
```
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mcrypt
memcache
memcached
mhash
mysql
mysqli
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

If I do cache & session to 'file' in local it works. As soon as I toggle it to memcache, every artisan command also throws ``` [ReflectionException]  Class cache does not exist ```

**Comment by shpasser** [comment]
First of all regarding 
`_PHPEnvironmentError: The PHP runtime cannot be run with the "Memcached" PECL extension installed`
Please take a look here: http://stackoverflow.com/questions/16625315/the-php-runtime-cannot-be-run-with-the-memcache-pecl-extension-installed
As you can see it is not related to the package.

**Comment by tusharvikky** [comment]
If I do comment out. I get 500 error with no log in apache2 error logs and so does in laravel error logs.

**Comment by shpasser** [comment]
Regarding running on the latest GAE `dev_appserver` please take a look here:
https://github.com/shpasser/GaeSupport/issues/7

**Comment by shpasser** [comment]
I find it more comfortable to develop using `laravel/homestead` VM. BTW, I do not use `memcached` in my local environment. But when running on GAE it both cache and session should use `memcached`.

**Comment by shpasser** [comment]
I suppose that in order to use GAE `dev_appserver` with `memcached` you will have to solve the configuration issue first. I can try to run one of my Laravel5 apps under `dev_appserver` on `laravel/homestead` VM later on.

**Comment by shpasser** [comment]
BTW, why not try `php artisan serve`?

**Comment by shpasser** [comment]
If I see no progress on this issue in 3 days I will have to close it. Please respond.

**Comment by tusharvikky** [comment]
Have to ditch it and use traditional VM machine.
