### ISSUE TITLE
preg_replace(): Compilation failed

### ISSUE THREAD

**Issue by WilliamChappell** [shpasser/GaeSupportL5#18]
When I try to generate the GAE related files, it creates the .env.local file, then throws an error of:

ErrorException] preg_replace(): Compilation failed: PCRE does not support \L, \1, \N{name}, \U, or \u at offset 4

Any ideas of how to fix this?

**Comment by shpasser** [comment]
In order to help I will need some mode information on the matter. Please describe your runtime environment e.g. Operation System, PHP version. In order to understand the issue I will also need to know more about your workflow e.g. the exact commands you ran(including the options) and the full error messages / stack traces you've got.

As of now it looks like an issue of PHP version vs code compatibility.

**Comment by shpasser** [comment]
Take a look at the following link, it might be of some help:
http://php.net/manual/en/reference.pcre.pattern.syntax.php#75339

**Comment by shpasser** [comment]
I just tried and was able to setup `gae-support-l5` on a fresh Laravel 5.1 app on `laravel/homestead 0.2.6` without any problems.

**Comment by WilliamChappell** [comment]
Ah, sorry I'm not using homestead for this project, I'm using windows and WAMP. PHP version 5.5.12. PCRE version is 8.34. I'm using a fresh install of Laravel. The exact command I'm using is:

php artisan gae:setup --config --cache-config --bucket='laravel-bucket' --db-socket="/cloudsql/laravel-test-996:laravel" --db-name='laravel_db' laravel-test-996

**Comment by shpasser** [comment]
My setup has PHP 5.6.7 and PCRE 8.35. Could you please send me the log file containing the error stack trace. The log files are placed by Laravel under `your-app/storage/logs` directory.

**Comment by WilliamChappell** [comment]
I've uploaded it to the following pastebin: http://pastebin.com/HkRvgbgT

**Comment by shpasser** [comment]
In `your-app/vendor/shpasser/gae-support-l5/src/Shpasser/GaeSupportL5/Setup/Configurator.php`
replace the function `fixCachedConfig()` with the following one:
```php
   protected function fixCachedConfig($contents)
    {
        $app_path = app_path();
        $storage_path = storage_path();
        $base_path = base_path();

        $strings = [
            "'${app_path}",
            "'${storage_path}",
            "'${base_path}"
        ];

        $replacements = [
            "app_path().'",
            "storage_path().'",
            "base_path().'"
		];

        $modified = str_replace($strings, $replacements, $contents);

        if ($contents !== $modified)
        {
            $this->myCommand->info('Generated "bootstrap/cache/config.php" for GAE deployment.');
            $this->myCommand->comment('* To use "bootstrap/cache/config.php" locally please regenerate it.');
        }

        return $modified;
    }
```
Please try again and let me know how it goes.

**Comment by WilliamChappell** [comment]
Thank you, that seems to have worked! Much appreciated.

**Comment by WilliamChappell** [comment]
A new issue though, when I push the project to GAE I get the following error though the GAE logs:

PHP Fatal error:  Invalid cloud storage bucket name ''laravel-bucket'' in /base/data/home/runtimes/php/sdk/google/appengine/api/cloud_storage/CloudStorageTools.php on line 500

**Comment by shpasser** [comment]
It looks like Windows paths are not so welcomed by `pre_replace()` because they contain back-slashes. I replaced `pre_replace()` with `str_replace()`, which is more than suitable in this case. Will push it to GitHub very soon as v1.3.1. Thanks.

**Comment by shpasser** [comment]
Do you have a GCS bucket named "laravel-bucket", did you actually created it?

**Comment by WilliamChappell** [comment]
I do have a bucket named laravel-bucket, I think the issue might be the double ' around the name of the bucket in the app.

**Comment by shpasser** [comment]
Sure, you should use it without double quote marks.

**Comment by WilliamChappell** [comment]
Sorry that was my fault. Re-running the GAE:setup with double quotes rather than single on the bucket name fixed that problem.

I've pushed the updated version to GAE and I'm now getting the error:

PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "gs://laravel-bucket/storage/logs/laravel-2015-07-05.log" could not be opened: failed to open stream: "\google\appengine\ext\cloud_storage_streams\CloudStorageStreamWrapper::stream_open" call failed' in /base/data/home/apps/s~laravel-test-996/1.385505260146663767/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:84
Stack trace:
#0 /base/data/home/apps/s~laravel-test-996/1.385505260146663767/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(88): Monolog\Handler\StreamHandler->write(Array)
#1 /base/data/home/apps/s~laravel-test-996/1.385505260146663767/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#2 /base/data/home/apps/s~laravel-test-996/1.385505260146663767/vendor/monolog/monolog/src/Monolog/Logger.php(269): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#3 /base/data/home/apps/s~laravel-test-996/1.38550526014666 in /base/data/home/apps/s~laravel-test-996/1.385505260146663767/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 84

Apologies for this.. I'm still learning laravel and GAE but do you have any ideas?

**Comment by shpasser** [comment]
Please send me the contents of your `.env` file.

**Comment by WilliamChappell** [comment]
http://pastebin.com/Jc6uedK0

**Comment by shpasser** [comment]
Please send me the contents of your `your-app/bootstrap/cache/config.php` file.

**Comment by shpasser** [comment]
I looks like `Monolog` is configured to use `file` instead of `syslog`. The `.env` file looks Ok, the next suspect is `your-app/bootstrap/cache/config.php`.

**Comment by WilliamChappell** [comment]
http://pastebin.com/7g3X5fGw

Really can't thank you enough for the help!

**Comment by shpasser** [comment]
It looks like we found it. Please send me your `.env.production` file, to make sure it Ok. `your-app/bootstrap/cache/config.php` is created according to `.env.production`. If `.env.production` is Ok will have to delete `your-app/bootstrap/cache/config.php`, regenerate it and push the app to GAE.

**Comment by WilliamChappell** [comment]
The .env.production is exactly the same as the .env file. To regenerate the cache/config.php file do I re-run the php artisan gae:setup command?

**Comment by shpasser** [comment]
`php artisan gae:setup --cache-config laravel-test-996` should be enough.

**Comment by WilliamChappell** [comment]
Ah, brilliant! I can now see laravel is running, but I'm afraid I'm getting another error.. It's saying the welcome view can't be found. The error is:

production.ERROR: exception 'InvalidArgumentException' with message 'View [welcome] not found.' in /base/data/home/apps/s~laravel-test-996/1.385505809250433181/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137 Stack trace: #0 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\View\FileViewFinder->findInPaths('welcome', Array) #1 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/vendor/laravel/framework/src/Illuminate/View/Factory.php(151): Illuminate\View\FileViewFinder->find('welcome') #2 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(614): Illuminate\View\Factory->make('welcome', Array, Array) #3 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/app/Http/routes.php(15): view('welcome') #4 [internal function]: App\Providers\RouteServiceProvider->{closure}() #5 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/vendor/laravel/framework/src/Illuminate/Routing/Route.php(155): call_user_func_array(Object(Closure), Array) #6 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/vendor/laravel/framework/src/Illuminate/Routing/Route.php(130): Illuminate\Routing\Route->runCallable(Object(Illuminate\Http\Request)) #7 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/vendor/laravel/framework/src/Illuminate/Routing/Router.php(704): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #8 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #9 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request)) #10 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #11 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request)) #12 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/vendor/laravel/framework/src/Illuminate/Routing/Router.php(706): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #13 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/vendor/laravel/framework/src/Illuminate/Routing/Router.php(671): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request)) #14 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/vendor/laravel/framework/src/Illuminate/Routing/Router.php(631): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request)) #15 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(229): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request)) #17 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request)) #18 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #19 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure)) #20 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array) #21 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(54): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #22 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure)) #23 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array) #24 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #25 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure)) #26 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array) #27 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #28 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure)) #29 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array) #30 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #31 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure)) #32 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array) #33 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #34 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure)) #35 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array) #36 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #37 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request)) #38 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #39 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(86): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request)) #40 /base/data/home/apps/s~laravel-test-996/1.385505809250433181/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request)) #41 {main} [] []

**Comment by shpasser** [comment]
Now I'll need `app.yaml` file please.

**Comment by shpasser** [comment]
BTW, what is the structure of filesystem tree in your GSC bucket under `storage`?

**Comment by WilliamChappell** [comment]
This is the app.yaml

http://pastebin.com/ckQJr7xE

**Comment by WilliamChappell** [comment]
The structure is: 
storage
-app
-framework
	-views

The app, framework and views folders are empty.

**Comment by shpasser** [comment]
`app.yaml` looks Ok. Please send `config/view.php`.

**Comment by shpasser** [comment]
`views` folder should contain the compiled views.

**Comment by WilliamChappell** [comment]
view.php - http://pastebin.com/ZmKADByr

**Comment by WilliamChappell** [comment]
The views folder is completely empty

**Comment by shpasser** [comment]
Please delete `config/cache/compiled.php`, push it to GAE and try again.

**Comment by shpasser** [comment]
I could see nothing wrong with configuration files, maybe it's again `config/cache/compiled.php`.

**Comment by WilliamChappell** [comment]
I don't seem to have a cache folder in the config folder?

**Comment by shpasser** [comment]
Sorry, `bootstrap/cache/compiled.php`.

**Comment by WilliamChappell** [comment]
I don't have a complied.php in the bootstrap/cache folder either

**Comment by shpasser** [comment]
Do you have `bootstrap/cache/services.json`?

**Comment by WilliamChappell** [comment]
Yes that's in there

**Comment by shpasser** [comment]
Please replace `findInPaths()` function in `vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php` with 
```php
    protected function findInPaths($name, $paths)
    {
        dd($paths);
        foreach ((array) $paths as $path) {
            foreach ($this->getPossibleViewFiles($name) as $file) {
                if ($this->files->exists($viewPath = $path.'/'.$file)) {
                    return $viewPath;
                }
            }
        }

        throw new InvalidArgumentException("View [$name] not found.");
    }
```
And let me know the results. (Added dump of $paths variable, so I can understand why it cannot find the view).

**Comment by WilliamChappell** [comment]
When I run the code on the local, I get: 

array:1 [▼
  0 => "C:\wamp\www\laravel\resources\views"
]

**Comment by shpasser** [comment]
Let me make sure, you see it while running on GAE, right?

**Comment by WilliamChappell** [comment]
Yes, the path is still C:/wamp/...

**Comment by shpasser** [comment]
Please let me see `your-app/bootstrap/cache/config.php` again.

**Comment by WilliamChappell** [comment]
http://pastebin.com/wHUHqBQN

**Comment by shpasser** [comment]
Please replace findInPaths() function in vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php with
```php
    protected function findInPaths($name, $paths)
    {
        foreach ((array) $paths as $path) {
            foreach ($this->getPossibleViewFiles($name) as $file) {
                if ($this->files->exists($viewPath = $path.'/'.$file)) {
                    return $viewPath;
                }
            }
        }

        throw new InvalidArgumentException("View [$name] not found.");
    }
'''
(Back to normal.)

**Comment by shpasser** [comment]
In your-app/vendor/shpasser/gae-support-l5/src/Shpasser/GaeSupportL5/Setup/Configurator.php
replace the function fixCachedConfig() with the following one:
```php
    protected function fixCachedConfig($contents)
    {
        $app_path = app_path();
        $storage_path = storage_path();
        $base_path = base_path();

        $strings = [
            "'${app_path}",
            "'${storage_path}",
            "'${base_path}"
        ];

        $replacements = [
            "app_path().'",
            "storage_path().'",
            "base_path().'"
		];

        dd($replacements);

        $modified = str_replace($strings, $replacements, $contents);

        if ($contents !== $modified)
        {
            $this->myCommand->info('Generated "bootstrap/cache/config.php" for GAE deployment.');
            $this->myCommand->comment('* To use "bootstrap/cache/config.php" locally please regenerate it.');
        }

        return $modified;
    }
```
Then please run `php artisan gae:setup --cache-config laravel-test-996` and let me know the results. I'm sure that `str_replace()` does not do the work, at least will understand why.

**Comment by shpasser** [comment]
Sorry, updated the last message.

**Comment by WilliamChappell** [comment]
It creates correctly and outputs:

array:3[
0 => "app_path().'"
1 => "storeage_path().'"
2 => "base_path().'"
]

**Comment by shpasser** [comment]
Apologies, I had a mistake, please re-run after the following change:
```php
    protected function fixCachedConfig($contents)
    {
        $app_path = app_path();
        $storage_path = storage_path();
        $base_path = base_path();

        $strings = [
            "'${app_path}",
            "'${storage_path}",
            "'${base_path}"
        ];

        $replacements = [
            "app_path().'",
            "storage_path().'",
            "base_path().'"
		];

        dd($strings);

        $modified = str_replace($strings, $replacements, $contents);

        if ($contents !== $modified)
        {
            $this->myCommand->info('Generated "bootstrap/cache/config.php" for GAE deployment.');
            $this->myCommand->comment('* To use "bootstrap/cache/config.php" locally please regenerate it.');
        }

        return $modified;
    }
```

**Comment by WilliamChappell** [comment]
That's ok :) This outputs:

array:3 [
0 => "'c:\wamp\www\laravel\app"
1 => "'c:\wamp\www\laravel/storage"
2 => "'c:\wamp\www\laravel"
]

**Comment by shpasser** [comment]
After finished, please remove `dd($strings);` line, delete `bootstrap/cache/config.php`, push the app to GAE and try running it again. This time it should work. I still have to figure out how to fix generation of `bootstrap/cache/config.php` on Windows.

**Comment by WilliamChappell** [comment]
Perfect! Everything displays correctly with no errors! Thank you so much!

**Comment by shpasser** [comment]
It is obvious that 'C:\\wamp\\www\\laravel' and 'c:\wamp\www\laravel' are not equal. First of all '\\' should be used instead of '\' and 'C:' and 'c:' should be treated accordingly(ignore case). It will take some time until I can make it work. As a workaround for now please do not use `--cache-config`. I will let you know when the fix is ready.

**Comment by WilliamChappell** [comment]
Thank you very much. I can finally start learning laravel properly for GAE. I look forward to your updates :)

**Comment by shpasser** [comment]
Just pushed an update to `dev-master`, which makes `--cache-config` windows compatible. Please check. Other updates were made, so please check the readme file before you update package.

**Comment by WilliamChappell** [comment]
Have just started a fresh laravel project and pulled in this package. Apparently it had no issues, however running through windows still throws up some errors. Running the project though GAE Launcher gives: file_put_contents(C:\wamp\www\laravel\storage/framework/views/340d30ff0757ece11e0c43a622752863): The local filesystem is readonly, open failed. This could be an issue with laravel on the launcher anyway, I've not tested that yet.

When pushing the project to the cloud I get: ErrorException in Filesystem.php line 81:
file_put_contents(): Exclusive locks may only be set for regular files.

Running the app though homestead still seems to work as normal.

**Comment by WilliamChappell** [comment]
Just tried the process again, it now has no issues running on GAE however local issue remains unchanged.

**Comment by shpasser** [comment]
This one is perfectly normal, since the local file system of the GAE Launcher is read-only. In order to use local filesystem in read-write manner you'll need to add the following line to the generated `php.ini`:
```php
google_app_engine.disable_readonly_filesystem = 1
```
This way the local filesystem will allow write operations. GAE production environment filesystem is not affected by this option and will remain read-only.

**Comment by WilliamChappell** [comment]
Ah thank you, everything appears to work now as intended :)
