### ISSUE TITLE
Gae Queue Connector throwing exception on construct

### ISSUE THREAD

**Issue by atrauzzi** [shpasser/GaeSupportL5#22]
It's expecting an instance of `Illuminate\Encryption\Encrypter` and getting `Illuminate\Contracts\Encryption\Encrypter` instead.

**Comment by shpasser** [comment]
I think you actually meant `Illuminate\Contracts\Encryption\Encrypter`.
I couldn't see any exceptions with my apps. They actually should not happen since the only mistake here is use of concrete class instead of contract, unless you were using some other encrypter?

**Comment by atrauzzi** [comment]
This is happening because some contracts in 5.1 were renamed from 5.0.

**Comment by shpasser** [comment]
I would like to reproduce the issue on my setup. Can you please tell me about your workflow, so I could reproduce the issue. I'm very curious on reproducing this one since I cannot see any reason for it to actually happen like I've mentioned before("...concrete class instead of contract").

**Comment by atrauzzi** [comment]
Gitter? :)

**Comment by shpasser** [comment]
Just pushed it to the master branch.

**Comment by atrauzzi** [comment]
:+1:
