### ISSUE TITLE
Null characters in serialized objects breaking queues

### ISSUE THREAD

**Issue by atrauzzi** [shpasser/GaeSupportL5#24]
When creating a queue job, I noticed that values are getting truncated.  Looking into this further, it appears as though PHP inserts `\x00` before private variables when using `serialize`.

Because Laravel depends on `serialize` functionality, it might be best if `GaeQueue` did a `base64_encode` when queueing and then a `base64_decode` when marshalling.  That way they won't cause parse errors when laravel calls `unserialize`.

**Comment by shpasser** [comment]
Could you please provide an example, so I could test it in my environment?
How is `memcached` connected to all that?

**Comment by atrauzzi** [comment]
Turns out this was OSX and possibly google app engine local dev related.

**Comment by shpasser** [comment]
I think issue #33 might be of interest for you. Looks like the same issue.
