### ISSUE TITLE
Class memcached required during artisan, but can't be used during live/local dev

### ISSUE THREAD

**Issue by atrauzzi** [shpasser/GaeSupportL5#25]
```
PHP Fatal error:  Class 'Memcached' not found in /home/atrauzzi/Development/project/vendor/shpasser/gae-support-l5/src/Shpasser/GaeSupportL5/Storage/CacheFs.php on line 85
```

This seems to be happening because I'm using artisan while my `.env` file configures things for a local GAE development server.

Because it's not currently possible to even run artisan in the GAE environment, would it make sense to disable any behaviour that depends on classes injected by the GAE environments when running via command line?

Caveat: We should be sure to only detect *real* command line and not get caught detecting when the commands facade is used during a request.

**Comment by atrauzzi** [comment]
Current workaround (although it requires muddling with system-level things):

```
sudo php5dismod memcached
sudo php5enmod -s cli memcached
```

**Comment by shpasser** [comment]
Ok, I think I have a solution for this one. Will push some changes in couple of hours.

**Comment by shpasser** [comment]
It is ready, please check.

**Comment by atrauzzi** [comment]
Checked out and it's great!  See my note on the commit, just in case you want to mention anything in the docs.
