### ISSUE TITLE
This error "file_put_contents(): Exclusive locks may only be set for regular files"

### ISSUE THREAD

**Issue by jjosephs** [shpasser/GaeSupportL5#26]
Just gave laravel5 on GAE a shot after a long break with a fresh blank install and I get this error

ErrorException in Filesystem.php line 81:
file_put_contents(): Exclusive locks may only be set for regular files

Any idea why?

**Comment by shpasser** [comment]
I tried to do a fresh blank install and it worked ok. In order to help I will need details on your development environment and exact workflow (the exact sequence of commands and configuration files changes). When I have the details I will try reproduce the issue and resolve it.

**Comment by jjosephs** [comment]
No worries, I switched over to AWS Beanstalk

**Comment by moston** [comment]
I have this issue right now. My laravel app is configured for memcache session but i've get this error:
![zrzut_ekranu-1](https://cloud.githubusercontent.com/assets/2960288/9175214/b66a1538-3f84-11e5-8d08-8772e2bd0e12.png)
