### ISSUE TITLE
file_put_contents(): Exclusive locks may only be set for regular files

### ISSUE THREAD

**Issue by moston** [shpasser/GaeSupportL5#27]
I have seen this issue here but it was fixed by using AWS. My laravel app is configured for memcache session but i've get this error:
![zrzut_ekranu-1](https://cloud.githubusercontent.com/assets/2960288/9175227/ce2ca168-3f84-11e5-9ccf-c122feb658c3.png)

It's fresh installation of laravel so I don't know what could be a problem. I've only configured GaSupport and this happens.

**Comment by shpasser** [comment]
It looks like your app is configured to use filesystem as session storage. Are you sure you copied / renamed your `.env.production` file to `.env` before the deployment?

**Comment by moston** [comment]
Yeah, I'm sure of it. I was changing values to other options but it doesn't work.

**Comment by shpasser** [comment]
In order to help I will need your configuration files: `.env`, `php.ini`, `app.yaml` and also cached configuration file `bootstrap/cache/config.php`.

**Comment by moston** [comment]
Ok my cached config.php was entries with using files. Fixed :)
