### ISSUE TITLE
Getting files from CloudStorage by Storage class

### ISSUE THREAD

**Issue by moston** [shpasser/GaeSupportL5#29]
Hi,

I have a problem with getting files by Storage class from Laravel. 

```php
Storage::disk('gae')->files('uploads/')
```

or 

```php
Storage::disk('gae')->get($path)
```

don't work and I'm getting FileNotFoundException. Am I doing something wrong ?

**Comment by shpasser** [comment]
While investigating the issue I found a bug preventing the filesystem from writing data to `gae` disk. Nevertheless the operations you perform should work properly as long as file `storage/app/{$path}` and directory `storage/app/uploads` really exist in your GCS bucket. I'm going to fix the `put/write` issue shortly, so you will be able to use `gae` to upload files too. Please notice that if your directory contains only other directories, but no regular files, `files()` function will return an empty list. For now, in order for your calls to succeed you could create directories and upload files to your GCS bucket using Google Developers Console.

**Comment by shpasser** [comment]
Please pull the newest version (1.4.1) via Composer.

**Comment by shpasser** [comment]
Please pull the newest version (1.4.2) via Composer(update to support disk root listing.)

**Comment by moston** [comment]
Great :) It's working :)
