### ISSUE TITLE
Wrong variable name on GaeJob class.

### ISSUE THREAD

**Issue by rulrok** [shpasser/GaeSupportL5#33]
I'm having some problems with serialization of objects using google app engine push queue.

The problem, I believe, is more related to laravel framework itself rather then this package.

I describe my problem thoroughly at [laravel/framework issue tracker](https://github.com/laravel/framework/issues/10081).

I just want to highlight something that I found on the plugin's code while debugging my problem.

On the class __GaeJob__, line 14 more specifically, we have this:

```php
<?php namespace Shpasser\GaeSupportL5\Queue;

use Illuminate\Container\Container;
use Illuminate\Queue\Jobs\Job;
use Illuminate\Contracts\Queue\Job as JobContract;

class GaeJob extends Job  implements JobContract {

	protected $qaeQueue;

	protected $job;

	protected $pushed = false;

	public function __construct(Container $container,
                                GaeQueue $gaeQueue,
                                $job,
                                $pushed = false)
	{
		$this->job = $job;
		$this->gaeQueue = $gaeQueue;
		$this->pushed = $pushed;
		$this->container = $container;
	}
```

Notice how the class property is declared as __$qaeQueue__, but within the controller it is referenced as __$this->gaeQueue__. I believe this could cause some eventual serialization issues, since the variable inside the controller is being created dynamically, rather than being attributed to the class's property __$qaeQueue__. I've changed your code and deployed my application again just to see if it would solve my problem and still I was getting the same problems (describe at the laravel framework issue tracker).

What solved my problem, though, was making a change in the laravel framework code. I suggest you to see my issue there for more details.

**Comment by shpasser** [comment]
Ok, I see. Thanks for locating the typo. I think that the typo should not affect serialization in this case. I saw the referenced issue, although it is not related to `gae-support-l5` package I would like to investigate it. Will keep you posted.

**Comment by shpasser** [comment]
Actually it looks like an issue with Google App Engine, please take a look:
https://code.google.com/p/googleappengine/issues/detail?id=12296

**Comment by shpasser** [comment]
Any progress? Just pushed the change. Please update to 1.4.4.

**Comment by shpasser** [comment]
I order to not mess the member visibility it is possible to replace `json_encode` with `base64_encode` in several places of the Queue related code or add an option to choose between the two. The problem with this approach is that it requires changes in several classes.

**Comment by atrauzzi** [comment]
Yeah, I just noticed that I'm encountering this issue now on real GAE environments.

I'm doing a `composer update` right now and will let you know if my queues start working again.  I assume all the existing jobs are toast?

**Comment by shpasser** [comment]
It depends if you have protected or private members in them.

**Comment by atrauzzi** [comment]
Interesting.  So this is something specific to `serialize` on GAE?

**Comment by shpasser** [comment]
As I see it is something specific to `json_decode()` function on GAE, it seems that the function does not parse properly JSON which includes `\u0000` characters.

**Comment by shpasser** [comment]
Looks like GAE' PHP is fixed now. I think that the problematic version was 5.5.27, currently my GAE app reports 5.5.26 as a part of `phpinfo()` and the problematic code `json_decode('{"\u0000": 1}');` does not cause errors anymore. I think it is time to close this one.

**Comment by atrauzzi** [comment]
Nice!  Now it's time for them to dig into the myriad of cURL related issues ;)
