### ISSUE TITLE
[ErrorException] escapeshellarg() has been disabled for security reasons

### ISSUE THREAD

**Issue by cedricziel** [shpasser/GaeSupportL5#36]
The error occurs when I execute *any* artisan command through the endpoint (which is logical to me).

Is this expected behaviour? The function is disabled in AppEngine and as far as I can tell it ever was.

**Comment by shpasser** [comment]
Please clarify on the way you execute artisan commands(the exact PHP code and how it is executed, a sample app would be great).  Have you tried to use `Artisan Console for GAE`, which is part of the package?

**Comment by cedricziel** [comment]
Sorry for being a bit unclear: I use the service provider endpoint and get the exception

**Comment by shpasser** [comment]
So, let me clarify:
1) your `config/app.php` contains the `Shpasser\GaeSupportL5\GaeArtisanConsoleServiceProvider`,
2) your `app.yaml` contains:
```yaml
        - url: /artisan
          script: public/index.php
          login: admin
          secure: always
```
3) when you enter URL http://your-app-id.appspot.com/artisan in your browser you see the `Artisan Console for GAE` form,
4) when you enter `list` command and execute it via the console you see `[ErrorException] escapeshellarg() has been disabled for security reasons` in the output window.

Am I correct?

**Comment by cedricziel** [comment]
Yes. - Absolutely correct.

**Comment by shpasser** [comment]
I could create a fresh Laravel 5.1 app, run `gae:setup` on it, deploy it on GAE and try to run some artisan command. Anyway in order to better understand the issue I would like you to send me a sample app which generates the error, so I could deploy it on GAE, inspect and debug.

**Comment by cedricziel** [comment]
Okay, let's hope the show effect kicked in and I made a mistake somewhere :)

I will try to create a sample ASAP.

**Comment by shpasser** [comment]
Thanks, I've already managed to locate the source of the issue:
https://github.com/laravel/framework/commit/a4dd6e6f193a09c6ac33e4ec70f5ca8c31606675

The commit is dated by Sep-17-2015, so it is relatively recent. And of course, the committed change makes use of unsupported `escapeshellarg()`, which is used by `ProcessUtils::escapeArgument()`.

I will have to see what are the possible fixes that can be applied.

Do you have any suggestions?

**Comment by cedricziel** [comment]
No, not really. :/

Yes, i saw those too, but didnt spend much attention to when it was committed.

**Comment by shpasser** [comment]
Ok I am going to see what can be down in order to "work around" the problem. Anyway, I do not really understand the actual value of that commit.

**Comment by cedricziel** [comment]
Thank you for taking care!

**Comment by shpasser** [comment]
Please update to version 1.4.8.

**Comment by tupperbear** [comment]
I'm using 1.4.10 and I am still getting the "escapeshellarg() has been disabled for security reasons" when trying to execute any artisan command on artisan console page.

**Comment by cedricziel** [comment]
Please have a look at #41. I think you still have the scheduled command activated
Am 20.11.2015 20:57 schrieb tupperbear <notifications@github.com>:I'm using 1.4.10 and I am still getting the "escapeshellarg() has been disabled for security reasons" when trying to execute any artisan command on artisan console page.

**Comment by tupperbear** [comment]
That did it! I wasn't aware there were any scheduling commands running by default. Thank you.
