### ISSUE TITLE
Adapt to Laravels log handler env variable

### ISSUE THREAD

**Issue by cedricziel** [shpasser/GaeSupportL5#37]
In laravel/laravel@8476df5c9eeb1489db64f7aa3456b38ae74d090d the environment variable `APP_LOG` was introduced.

GaeSupport can now simply adapt it as the replacement is broken as well.

**Comment by shpasser** [comment]
Thanks. I'm going to reformat and rearrange the Configurator class and incorporate the suggested changes very soon.

**Comment by shpasser** [comment]
As well I will have to update the tests.

**Comment by shpasser** [comment]
Please update to version 1.4.9.

**Comment by cedricziel** [comment]
Thx :)

**Comment by shpasser** [comment]
Shortly after the update the following issue arrived #39. It seems that it is not that simple as we thought. I will have to make a change to bring back `setLogHandler()`, but the env variable name will sill be `APP_LOG`.
