### ISSUE TITLE
[DOC] On commands and artisan console

### ISSUE THREAD

**Issue by cedricziel** [shpasser/GaeSupportL5#41]
The laravel 5 skeleton ships a default "inspire" quote which is scheduled to run hourly. On any artisan command, the scheduler is checked for execution which results in invocation of ``InspireCommand`` which still uses ``escapeshellarg()``.

Conclusion: One needs to remove the command from the scheduler in ``app/Console/Kernel``. (I still wonder if this means we cannot have scheduled commands at all).

**Comment by shpasser** [comment]
Please read the last section of the readme file.

**Comment by cedricziel** [comment]
Alright - thanks a bunch. My mistake :)

For beginners it might be hard to debug why artisan dies. Can you a section on why and where scheduled commands need to be removed? - Just like the above. I was hesitating to Pull-Request it.

**Comment by shpasser** [comment]
No problem, I will add some clarifications very soon.

**Comment by shpasser** [comment]
Done.

**Comment by cedricziel** [comment]
Great - thx!
