### ISSUE TITLE
Class 'Dotenv' not found      

### ISSUE THREAD

**Issue by deven003** [shpasser/GaeSupportL5#45]
I am getting following error while running 
    
    php artisan gae:setup --config --cache-config --bucket="your-bucket-id" --db-socket="cloud-sql-instance-socket-connection-string" --db-name="cloud-sql-database-name" app-id

    PHP Fatal error:  Class 'Dotenv' not found in /var/www/anglist/vendor/shpasser/gae-support-l5/src/Shpasser/GaeSupportL5/Setup/Configurator.php on line 69
                                                           
      [Symfony\Component\Debug\Exception\FatalErrorException]  
     Class 'Dotenv' not found                                 

I am using Laravel 5.2

**Comment by shpasser** [comment]
As of now the package is not compatible with Laravel 5.2. Larvel 5.2 makes use of a newer version of Dotenv. I am still working on support for Laravel 5.2 and it is not yet ready. Very soon I'm going to create a new branch called 5.2 in order to maintain Laravel 5.2 compatible version of the package. Since Laravel 5.1 is LTS the current version of the package is here to stay.

**Comment by deven003** [comment]
thanks @shpasser for the update. Keep up the good work.

**Comment by suku-h** [comment]
Hey has the dotenv update for laravel 5.2 completed?

**Comment by shpasser** [comment]
Not yet, last two months I was too busy, to release a 5.2 compatible version. I hope to get it done in two weeks.

**Comment by agentmilindu** [comment]
Hi @shpasser, how is the developments going on for 5.2 support? :) Badly wanting to move to 5.2 on GAE. And we too can contribute :)

**Comment by shpasser** [comment]
Certainly, I would appreciate if you could help me to test and fix the new version before I publish it as stable.

**Comment by agentmilindu** [comment]
@shpasser Of coerce, with pleasure! :D I have a Laravel 5.2 app awaiting to be deployed on GAE, stuck with this `Class 'Dotenv' not found` error. If you can push your 5.2 branch, we can help you with testing and fixing :)

**Comment by shpasser** [comment]
Please start testing the first update was already pushed to master branch.

**Comment by agentmilindu** [comment]
Hi @shpasser, we are still working on this. We migrated to 5.2 from 5.0 we had to do lot of changes in our controllers and Auth model. Now we could reach where we use the Queues and Emailing! :D They too works nice! :D

**Comment by shpasser** [comment]
Thanks for the update.

**Comment by agentmilindu** [comment]
We previously used Mailgun for sending emails. Is there any limitations in GAE mailer? Can we change the name of the sender to something sensible rather `admin@<app-id>.appspotmail.com`? We can use it instead of `gae`, right?

**Comment by agentmilindu** [comment]
Hi @shpasser, when using Mailgun as email provider, I'm getting the following error. It seems the problem is with Guzzle's HTTPS. 

> production.ERROR: exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `POST https://api.mailgun.net/v3/rsvp.lk/messages.mime` resulted in a `401 Unauthorized` response: Forbidden

I tried using cUrlLite also, that also gives errors. It is really good if we can ucs cUrlLite. Can we do something for this?

**Comment by shpasser** [comment]
Hi @agentmilindu I would prefer to stop discussing the issues here, please open separate issues for every topic, so we could discuss them in a proper manner. Anyway, I will look into the mail related issue.
