### ISSUE TITLE
 error: ErrorException in Filesystem.php

### ISSUE THREAD

**Issue by fede3u** [shpasser/GaeSupportL5#46]
When installed I get this error: ErrorException in Filesystem.php line 81:
file_put_contents(): Exclusive locks may only be set for regular files

works fine in localhost but as soon as i push it to GAE i get this error, please help thx
<img width="971" alt="screen shot 2016-02-25 at 10 44 11 pm" src="https://cloud.githubusercontent.com/assets/17490068/13345143/53db975a-dc11-11e5-8581-26c757caa02d.png">

**Comment by shpasser** [comment]
Looks like you pushed to GAE a wrong `.env` file. Please make sure you use the generated one named `.env.production`. Please rename it to `.env` before you push it.  While running on GAE `memcached` should be used as session driver(this is how I know that your `.env` file is not correct). And one more thing, since Laravel 5.2 is not yet supported please use 5.1. I hope to add support for 5.2 very soon.

**Comment by fede3u** [comment]
Thx Shpasser, I m using L4.1 and the the file pushed is the .env with the content of the env.production, here for reference:

APP_ENV=production
APP_DEBUG=false
APP_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
DB_HOST=
DB_DATABASE=fede
DB_USERNAME=root
DB_PASSWORD=
CACHE_DRIVER=memcached
SESSION_DRIVER=memcached
QUEUE_DRIVER=gae
MAIL_DRIVER=gae
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=
APP_LOG=syslog
FILESYSTEM=gae
DB_CONNECTION=cloudsql
DB_SOCKET=/cloudsql/fedecoder:fede
CACHE_SERVICES_FILE=false
CACHE_CONFIG_FILE=false
CACHE_ROUTES_FILE=false
CACHE_COMPILED_VIEWS=false

**Comment by shpasser** [comment]
If you are using Laravel 4.1 then the right package for you is shpasser/GaeSupport.
shpasser/GaeSupportL5 is for 5.1

**Comment by fede3u** [comment]
sorry i ment 5.1

**Comment by shpasser** [comment]
Then probably you have a cached config file `bootstrap/cache/config.php`. Please remove it or regenerate it using `php artisan gae:setup --cache-config <<app-id>>` before pushing your app to GAE.

**Comment by shpasser** [comment]
BTW, sqlite is not supposed to work on GAE.

**Comment by fede3u** [comment]
awesome works thx Shpasser that was the issue .... btw when will you come out with the 5.2 integration package?

**Comment by shpasser** [comment]
Started working on it, I was very busy for the last 3.5 months. If you would like you could start testing the master branch with 5.2 and help me make it work with 5.2.
