### ISSUE TITLE
GAE:setup unexpected '=' syntax error

### ISSUE THREAD

**Issue by clee231** [shpasser/GaeSupportL5#51]
Using a fresh Laravel 5 installation, it seems that the GAE:setup command will fail due to a change with how application keys are generated.  The error is now as follows:
> $ php artisan gae:setup testme-961 --config --cache-config
>
>
> [ErrorException]
>   syntax error, unexpected '=' in /cygdrive/c/nginx-1.9.9/html/testme/app/../.env on line 3

Application keys are now encoded with base64 with seems to have an '=' symbol at the end of the string.

For example:
When I generate a new key via artisan (`php artisan key:generate`), something along the lines of the following gets placed on the third line of the default .env file:
```
APP_KEY=base64:QQLFuWBMqP2EqMpmVKhlZWdEC+2QzW534//lsCWQ57s=
```

I haven't had time to take a through look at the code yet, but I think it might have to due with the InitHelper class.  This implementation may not support reading in strings with multiple '=' symbols within the line.

----
Notes on my current setup:

- PHP  5.6.20
- Windows 10
- Cygwin
- Nginx 1.9.9
- Laravel 5.2.32

**Comment by clee231** [comment]
After reading the description a bit more, I realized that this is only for Laravel 5.1 LTS... Sorry for my misunderstanding...

**Comment by shpasser** [comment]
Try the `dev-master` version it already has some 5.2 related changes.

**Comment by clee231** [comment]
Yes, this seems to be no longer an issue after pulling from the latest development branches.  Sorry for the confusion.
