### ISSUE TITLE
Issues writing log files

### ISSUE THREAD

**Issue by josh18** [shpasser/GaeSupportL5#60]
When trying to write a log I get the error message:
```
PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "gs://splink/storage/logs/laravel.log" could not be opened: failed to open stream: "\google\appengine\ext\cloud_storage_streams\CloudStorageStreamWrapper::stream_open" call failed' in [path]/bootstrap/cache/compiled.php:13906
```
I assume there is something wrong with my configuration, any idea what I could be doing wrong?

--
**.env**
```
...
LOG_HANDLER=syslog
```

**config.app.**
```
...
'log' => env('LOG_HANDLER', 'daily'),
```

**Pre-deploy commands**
```
php artisan gae:setup cache-config
php artisan route:cache
php artisan optimize
```

Let me know if there is any other information that I can provide that would be helpful.

**Edit**
Note that I'm on Laravel 5.2 which I just realised isn't supported at the moment so that could be the issue.

**Comment by shpasser** [comment]
Hi, it looks like the log is not configured properly.
The log is using file instead of syslog driver. Please run

`php artisan gae:setup cache-config`

and check if the configuration cache is generated correctly.

**Comment by josh18** [comment]
I ran `php artisan gae:setup cache-config` and these changes happened:

**config/app.php**
```
'log' => env('LOG_HANDLER', 'daily'),
->
'log' => env('APP_LOG', 'daily'),
```

**config/view.php**
```
'compiled' => env('COMPILED_PATH', storage_path().'/framework/views'),
->
'compiled' => env('CACHE_COMPILED_VIEWS') ?
    Shpasser\GaeSupportL5\Storage\Optimizer::COMPILED_VIEWS_PATH :
    storage_path('framework/views'),
```
And then I manually renamed `COMPILED_PATH` and `CACHE_COMPILED_VIEWS` in my `.env` file.

--

It seems to be working now. Maybe when `php artisan gae:setup cache-config` is run in my build (inside Jenkins) the variables in the config were being renamed but not the variables in `.env`, do you think that would cause this issue?

Is `php artisan gae:setup cache-config` supposed to generate a file `bootstrap/cache.config.php` like `php artisan config:cache`? Or what is it supposed to do?

**Comment by josh18** [comment]
Sorry I just realised I was doing it wrong 😟 .

It is supposed to be `php artisan gae:setup --cache-config <app-id>`, not sure where I got the other command from.
