### ISSUE TITLE
Laravel with app engine supports few simultaneous requests per instance?

### ISSUE THREAD

**Issue by corocraft** [shpasser/GaeSupportL5#61]
I have a problem with the instances.
I set GAESupportL5 optimized with the tips of you. I use a F4 instance that supports approximately 15 simultaneous requests per instance and then it does autoscaling. I think is not normal (so few simultaneous requests per instance),did someone happen to this?

**Comment by shpasser** [comment]
Sorry, I don't understand the question. Could you please rephrase and give more information on what you expect vs what actually happens. Also, please describe your workflow and the kind of requests you are sending.

**Comment by corocraft** [comment]
Ok, i will try to explain myself clearly

We installed laravel in App Engine using the documentation of GaeSupportL5. When we did stress test, the response of laravel was 15 request per instance and then it scaled to another new instance. We thought that it is very few, i mean, the number of request by instancy is too little.

According your experiencie, how many simultaneous request could handle App Engine per instance with Laravel?  

Our currently instance is F4 and we have already done the optimizations recommend by the documentation to have better response times .

**Comment by shpasser** [comment]
The optimizations that I include in the package were made in order to optimize the time of a single request. The matters you are talking about are connected to GAE instance scaling behaviour. I think you should read the latest GAE documentation on the matter in order to get the answers.

I would start here: https://cloud.google.com/appengine/docs/php/an-overview-of-app-engine.

GaeSupportL5 optimizations were mostly implemented based on discussion: #3

**Comment by corocraft** [comment]
I understand but i would like to know, what is the average of simultaneous request that laravel could handle in GAE?
It is only to have a reference and to know if the simultaneous request that i already have are normal or i could get more simultaneous request with laravel in GAE. That's because i used laravel in a virtual machine  and with similar conditions gets better performance (simultaneous request) that in GAE.

**Comment by shpasser** [comment]
Sorry, I cannot answer that, because I have not run that kind of tests on GAE.

**Comment by shpasser** [comment]
I think it is time to close this one...
