### ISSUE TITLE
Artisan console for local development

### ISSUE THREAD

**Issue by josh18** [shpasser/GaeSupportL5#62]
The artisan console doesn't seem to work in local development, whenever I try to use it I get the error:
`[ErrorException] escapeshellarg() has been disabled for security reasons`

I narrowed it down to [this line](https://github.com/shpasser/GaeSupportL5/blob/master/src/Shpasser/GaeSupportL5/Queue/Listener.php#L22) so it looks like it is turned off intentionally?

The reason I want to use it in local development is so that I can upload a file to Cloud Storage (local) when I run `php artisan db:seed`. However if I do this from the command line I get the error `Unable to find the wrapper "gs" - did you forget to enable it when you configured PHP`.

**Comment by shpasser** [comment]
It looks like you use GAE SDK for local development. Am I right?

**Comment by josh18** [comment]
Yup that's right.

**Comment by shpasser** [comment]
Actually I built it so it would be possible to use it for apps actually running on GAE. For local environment I would just use the regular `php artisan`.
