### ISSUE TITLE
Db Socket question app-id

### ISSUE THREAD

**Issue by davedriesmans** [shpasser/GaeSupportL5#67]
For the db-socket you want this format:

```/cloudsql/app-id:cloud-sql-instance-name```

i have an 'unable to find the socket transport \"unix\ ... ' error so want to be sure that my setting is correct.

```cloud-sql-instance-name```: can be found in SQL
```app-id```: not sure where to find this. is it like appname.appspot.com or the appname from appname.appspot.com ? tried a couple of things here

**Comment by shpasser** [comment]
You are supposed to obtain the needed information from GAE SQL configuration screen. 
Please notice "Instance connection name" (grey background selection)

![cloudsql_config](https://cloud.githubusercontent.com/assets/4275204/20763566/3d090208-b733-11e6-816e-65a25a5dbcb8.png)

**Comment by skipatrol** [comment]
I can confirm that when running the `gae:setup` command the highlighted portion in shpasser's screenshot is the format that works for me for the db-socket config - I've never used the keyword "cloudsql" or any forward slashes.  The app-id is the GAE project id, in the case of shpasser's screenshot if the intent is to deploy to the same application that's hosting the CloudSQL instance it would be `laratest52`

**Comment by shpasser** [comment]
Please read the following:
https://cloud.google.com/appengine/docs/php/cloud-sql/

**Comment by davedriesmans** [comment]
Thanks, that screenshot was perfect. Got it working
Also, maybe interesting for those struggling. When manually editing the .env, clear the config cache before deploying ;)
