### ISSUE TITLE
Do you know if the package works with App Engine Flexible Environment?

### ISSUE THREAD

**Issue by mgallegos** [shpasser/GaeSupportL5#69]
PHP App Engine Flexible Environment documentation: 

https://cloud.google.com/php/getting-started/hello-world#running_php_apps_in_the_google_app_engine_flexible_environment

**Comment by shpasser** [comment]
No, but I'm going to check if it does.

**Comment by mgallegos** [comment]
Thanks, by the way I found the example for Laravel:

https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/appengine/flexible/laravel

**Comment by shpasser** [comment]
Looks interesting. Maybe finally my package is not needed anymore and it is possible to run full Laravel app on AppEngine without any twiks.

**Comment by mgallegos** [comment]
I'm testing it now, everything seems to works out of the box, except using the google cloud storage, I tried using your package but it didn't work.

They provide an example in the following link, I'm going to explore it and try to work something out:

https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/appengine/flexible/storage

**Comment by erandagan** [comment]
@mgallegos Could you provide more information regarding your experience with Laravel and GAE Flex? I'm considering a migration of a production GAE app running Laravel to the Flexible Environment

**Comment by mgallegos** [comment]
@erandagan it is pretty straight forward, take a look at the [Laravel example](https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/appengine/flexible/laravel), and to use google cloud storage I found this package: [Superbalist / laravel-google-cloud-storage](https://github.com/Superbalist/laravel-google-cloud-storage)

**Comment by erandagan** [comment]
@mgallegos I hope It's not getting too much off-topic, but my main concern was whether all the local files (cached config, etc) are saved on the machine running the server, or on GCS (since one of the major issues GaeSupport solves the slow access to GCS for file operations)

**Comment by mgallegos** [comment]
For what I've seen so far it's seems they are saved on the machine running the server. I've been testing the response time and it's feels a lot faster.

**Comment by cassina** [comment]
@erandagan Do you have an update on the migration of your app? I´m testing a migration to GAE Flex also. Currently it´s working OK , doing some work around on some config issues with sessions. will add the GCS package mentioned by @mgallegos.

**Comment by erandagan** [comment]
Hi @cassina, not yet. I've decided to wait with the migration until GAE Flex is more mature, since I'm migrating a backend which serves tens of thousands of clients. Rather not migrate while Flex is still in beta...

Which issues did you encounter?
