### ISSUE TITLE
Does package allow to upload files?

### ISSUE THREAD

**Issue by makss87** [shpasser/GaeSupportL5#70]

**Comment by shpasser** [comment]
The answer is yes, but there are several options with their limitations. Please take a look at the following link:
https://cloud.google.com/appengine/docs/standard/php/googlestorage/user_upload

**Comment by makss87** [comment]
Thanks a bazillion!

**Comment by shpasser** [comment]
Try reading the following https://cloud.google.com/appengine/docs/standard/php/googlestorage/#is_there_any_other_way_to_read_and_write_files
