### ISSUE TITLE
isRunningOnGae() error

### ISSUE THREAD

**Issue by McGreeb** [shpasser/GaeSupportL5#72]
Hi there,

Used your plugin but am now trying on the flexable enviroment and doent need it.

am getting the error Call to undefined method Illuminate\Foundation\Application::isRunningOnGae()

any idea how to restore my project to before I installed your plugin?

**Comment by shpasser** [comment]
I think that the best way would be to create a new project and move your app files there. I do not see a simple way of undoing the changes in configuration files.

**Comment by shpasser** [comment]
If you did not remove the backup files than you may still have the original configuration files.
