### ISSUE TITLE
There are no commands defined in the "gae" namespace - Error

### ISSUE THREAD

**Issue by oberoivarun** [shpasser/GaeSupportL5#75]
Laravel 5.5

I did:

`compose require shpasser/gae-support-l5`
Then added `Shpasser\GaeSupportL5\GaeSupportServiceProvider::class,` to config/app.php providers array.

Then i tried the `php artisan gae:setup` command with my appropriate values as described in the ReadMe file. I got this error:

`There are no commands defined in the "gae" namespace.`

I tried `php artisan clear-compiled`, `composer dump-autoload`. No help, still the same error.

What am i doing wrong?

**Comment by shpasser** [comment]
I haven't tested the package with Laravel 5.5 because it requires PHP version higher than 5.5 (which is the one supported by GAE). In any case the behavior you describe is not the one I would expect, so I'll try to check it ASAP and get back to you.

**Comment by shpasser** [comment]
BTW, the latest version of Laravel the package is known to work with is 5.2.

**Comment by oberoivarun** [comment]
That's a bummer. 

BTW, GAE now supports upto PHP 7.2 in a flexible environment. 
https://cloud.google.com/appengine/docs/php/

**Comment by shpasser** [comment]
I've not tried the flexible environment, but as far as I understand it should be able to run Laravel 5.5 as-is without my package.

**Comment by shpasser** [comment]
If you have a problem running Laravel in flexible environment I would appreciate if you let me know.

**Comment by oberoivarun** [comment]
No, i got it working. But your package makes it easy to integrate the queue and file system from GAE. I'm yet to figure those out. If you have any good articles/tutorials which you can refer that'll be great. All i am finding are at least a year old.

**Comment by shpasser** [comment]
Please try pulling `composer require shpasser/gae-support-l5:dev-master`. It contains changes that will allow the package provider to register `artisan` commands with Laravel 5.5. Then you can run the commands, although I've not tested the results under Laravel 5.5.
