### ISSUE TITLE
Google Cloud Datastore support?

### ISSUE THREAD

**Issue by coccoinomane** [shpasser/GaeSupportL5#76]
Hello,
First of all thanks for the effort of adapting Laravel for GAE!

Is Google Cloud Datastore supported at the Eloquent level?
If not, do you know how difficult it would to support it?

Cheers,
Guido

**Comment by shpasser** [comment]
If by "Google Datastore" you mean "cloudsql" the answer is yes. Please notice that Laravel 5.1 and partially 5.2 are supported, but not the latest versions. Regarding the use of "cloudsql" please take a look at the readme document. Since this is a question and not an issue I'm closing it.

**Comment by coccoinomane** [comment]
Hi shpasser, thank you for your reply.

I actually meant Google Cloud Datastore (https://cloud.google.com/datastore/docs/concepts/overview), the noSQL database by Google.

I will assume it is not supported, no problem.

There is a Laravel package to support it (https://github.com/dalejmooney/laravel-google-datastore/tree/master/src/GoogleDatastore), will look into it.

Cheers,
Guido
