### ISSUE TITLE
Working with development server

### ISSUE THREAD

**Issue by gpolguere** [shpasser/GaeSupportL5#9]
Hello,
I'm trying to use the support package (I'm using the last commit on dev-master) but can't figure out how to get it working on the development server.
For comparison, I have set up a vhost and it works but when running it with the development server, I have this error :
```
ErrorException in Filesystem.php line 74:
file_put_contents({project_folder}/storage/framework/views/7c11e7f8cc1fcffb56a1755ae0ee5b19): The local filesystem is readonly, open failed
```
So, is the support package supposed to be working with development server? If so, do you have any idea why I have this error ?
Thank you!

**Comment by shpasser** [comment]
I think, I might have an idea. It seems that the development server does not allow to write files on local file system anymore. I could see this kind of behavior while trying to run my apps on development server using php55.

My suggestion is to use `homestead` as your local development environment. It works even after running `php artisan gae:setup` command as long as you copy / rename the generated `.env.local` to `.env` before using / testing your app.

**Comment by gpolguere** [comment]
I already have a local development environment working. But I'm not very familiar with GAE and when deploying, I'm having some troubles like
`file_put_contents(): Exclusive locks may only be set for regular files`

**Comment by shpasser** [comment]
In order to try to help you I would need more info about your workflow, i.e. the commands you execute and the configurations you perform including `appcfg.py update ./` and such. The syslog entries from GAE could help a lot.

**Comment by shpasser** [comment]
Sometimes a wrong use of `appcfg.py` command can cause a lot of troubles.

**Comment by gpolguere** [comment]
I have the last version of lavarel/framework v5.0.28.
I perform a `appcfg.py update . `
Here is the log :
```
local.ERROR: exception 'ErrorException' with message 'file_put_contents(): Exclusive locks may only be set for regular files' in /base/data/home/apps/e~{{app-id}}/1.383762485434776300/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:74 Stack trace: #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/base/data/home...', 74, Array) #1 /base/data/home/apps/e~{{app-id}}/1.383762485434776300/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(74): file_put_contents('gs://{{gcs-id}}/st...', 'a:4:{s:6:"_toke...', 2) #2 /base/data/home/apps/e~{{app-id}}/1.383762485434776300/vendor/laravel/framework/src/Illuminate/Session/FileSessionHandler.php(70): Illuminate\Filesystem\Filesystem->put('gs://{{gcs-id}}/st...', 'a:4:{s:6:"_toke...', true) #3 /base/data/home/apps/e~{{app-id}}/1.383762485434776300/vendor/laravel/framework/src/Illuminate/Session/Store.php(255): Illuminate\Session\FileSessionHandler->write('10a42a3227644fa...', 'a:4:{s:6:"_toke...') #4 /base/data/home/apps/e~{{app-id}}/1.383762485434776300/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(89): Illuminate\Session\Store->save() #5 /base/data/home/apps/e~{{app-id}}/1.383762485434776300/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(135): Illuminate\Session\Middleware\StartSession->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response)) #6 /base/data/home/apps/e~{{app-id}}/1.383762485434776300/public/index.php(57): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response)) #7 {main} [] []
```
app.yaml
```
application:    {{app-id}}
version:        1
runtime:        php55
api_version:    1

handlers:
        - url: /favicon\.ico
          static_files: public/favicon.ico
          upload: public/favicon\.ico

        - url: /css
          static_dir: public/css

        - url: /fonts
          static_dir: public/fonts

        - url: /.*
          script: public/index.php

skip_files:
        - ^(.*/)?#.*#$
        - ^(.*/)?.*~$
        - ^(.*/)?.*\.py[co]$
        - ^(.*/)?.*/RCS/.*$
        - ^(.*/)?\.(?!env).*$
        - ^(.*/)?node_modules.*$
        - ^(.*/)?_ide_helper\.php$

env_variables:
        GAE_CACHE_SERVICES_FILE: true
        GAE_CACHE_CONFIG_FILE: true
        GAE_CACHE_ROUTES_FILE: true
        GAE_SKIP_GCS_INIT: true
```
Let me know if you need any more info!

**Comment by shpasser** [comment]
I would need the generated `php.ini` too.

**Comment by shpasser** [comment]
And the deployed `.env` file also.

**Comment by shpasser** [comment]
If you managed to solve the problem please let me know.
I am going to close the issue if it will remain inactive for the next 5 days.

**Comment by codemonkeynorth** [comment]
I'm not sure if this helps but if you are using the Google Cloud SDK shell you can add this to php.ini to enable write access (obviously this won't work on an actual GAE live instance and you should use cachefs or buckets etc)

`google_app_engine.disable_readonly_filesystem=1`

however I was hoping it might be possible for GaeSupportL5/GaeSupportLumen to detect this SDKenvironment better and also allow memcached to be used for caching templates etc. 

I'm assuming this is related in some way anyway

https://github.com/shpasser/GaeSupportLumen/issues/6

thanks
J
